#!/bin/sh

if ls --classify >& /dev/null; then
    alias ls='ls --classify --color=auto'
else
    alias ls='ls -hG' # More?
fi
alias ll='ls -l'
alias la='ls -a'
alias lA='ls -A'

alias RM='rm -rf'

alias -- +x='chmod +x'
alias -- -x='chmod -x'
alias -- +r='chmod +r'
alias -- +rX-R='chmod +rX -R' # make dirs +rx, files +r

alias ..='cd ..'
alias ..1='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'
alias ..6='cd ../../../../../../..'
alias ..7='cd ../../../../../../../..'
alias ..8='cd ../../../../../../../../..'
alias ..9='cd ../../../../../../../../../..'
