#!/bin/sh
alias ll='ls -l'
alias la='ls -a'
alias lA='ls -A'

alias RM='rm -rf'

alias -- +x='chmod +x'
alias -- -x='chmod -x'

alias ..='cd ..'
alias ..1='cd ..'
alias ..2='cd ../..'
alias ..3='cd ../../..'
alias ..4='cd ../../../..'
alias ..5='cd ../../../../..'
alias ..6='cd ../../../../../..'
alias ..6='cd ../../../../../../..'
alias ..7='cd ../../../../../../../..'
alias ..8='cd ../../../../../../../../..'
alias ..9='cd ../../../../../../../../../..'
